spring:
  datasource:
    url: jdbc:postgresql://db:5432/restaurant_db
    username: postgres
    password: 097968
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090
